### ISSUE TITLE
Sepia overlay doesn't cover the full screen

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#20]
There is that sepia overlay in the past and also that flash when you change the time. On my screen, this overlay doesn't cover the whole screen, there is a small section at the top and bottom that is left empty.

My resolution is 2560×1400 (16:9 aspect ratio).

**Comment by Warr1024** [comment]
There is actually a general problem across the game of using HUDs with fixed scaling instead of using the "stretch to fit screen" negative values.  These can lead to distortion in theory, but common screen aspect ratios are easy enough to guess (almost everyone is close enough to 16:9 these days) and basically all of the HUDs used in this game (even the ghost speech) will tolerate some apsect ratio distortion and still be quite usable.

**Comment by Warr1024** [comment]
This should be fixed in 768387b2b6a35fad893d71e0295bc7803b2a3c33, now in main.
