### ISSUE TITLE
"HUD hidden" and (not)FullHD screenshot

### ISSUE THREAD

**Issue by andyca111100** [Irevol/minetest-citadel#39]
I have tried to remove "HUD Hidden" with GIMP to make a PR, but failed. Also, screenshot is not 1920*1080, but 1920*1017, so remaking the screenshot would be nice. Using a screenshot from the game itself would be enough, but remaking the scene in Blender (or any other 3D graphics software) would give an oportunity to make a 4K version of it (for those rich ones who have a 4K monitor). Would make a great wallpaper imho.

**Comment by Warr1024** [comment]
You don't actually want to overdo it with the screenshot since it makes it take longer to load the CDB page.  1080p is fine.  It would be nice to take a high quality webp with antialiasing and such, to best balance quality and download size.  It's not really necessary to go to all the trouble to use blender though, and it's really best if the screenshot just accurately depicts what the game would actually look like.

**Comment by andyca111100** [comment]
The screenshot is also used on Main Menu screen, by the way. Won't ones with displays with higher resolution than 1080p (1440p for example, which I totally forgot about) have any problems?

**Comment by Warr1024** [comment]
I use 360p screenshots for the main menu.  Long download times from CDB are worse than somewhat grainy backgrounds. You can't use webp for in-game stuff so you're stuck with either PNG or JPEG here, and these background shots can quickly become a significant chunk of the package download time, without adding any actual gameplay value.

If somebody is going to look at the package and then decide against downloading it because of the size, you want to get something really important in exchange for that.

Also we don't want to use huge images because MT will load those entirely into RAM and that's not really a good use or memory either.

**Comment by Irevol** [comment]
I got rid of the "hud hidden" label, for now I think the screenshot quality is fine.
