### ISSUE TITLE
Warning spam: Packet quota used up

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#7]
The game is spamming a lot of warnings in the console. They look like this:

```
Warning spam: WARNING[ConnectionSend]: con(15/1): Packet quota used up for peer_id=2, was 1024 pkts
```

I guess this might be a performance problem?

Found in the game jam version.

**Comment by Warr1024** [comment]
It looks like the way fading in/out works is that rather than updating the HUD every step, it sends a massive burst of HUD changes on a single step, and apparently relies on the client to process those asynchronously across multiple frames.

The "fade out" part of the process seems to be done more correctly, i.e. using minetest.after, so I'm not sure why the "fade in" was done this way.

I have examples of better HUD fades in ColourHop (ch_flashscreen), NodeCore SkyRealm, and Klots (I don't remember which mod; klots_player maybe?), though in my case I always _cut_ to black and then fade back in.  A fade-out-fade-in would be achieved by just using a different piecewise-linear function for the opacity over time.

**Comment by Warr1024** [comment]
I filed separate issue #11 for the confirmed performance impact of the HUD logic, but the packet spam itself doesn't seem to cause any notable performance issues.  When I changed the opacity to round to the nearest 32, almost all of the lag is gone after time-traveling about 3 or 4 times (due to all the images finally being cached) even though it still sends the same packet bursts.
